In [1]:
import gym
import json
import datetime as dt
import numpy as np
import pandas as pd
import tensorflow as tf
import os
from gym import wrappers




In [2]:
from env.StockTradingEnv import StockTradingEnv
from networks.DQNac import MyModel
from networks.DQNac import StockActor, StockCritic

In [3]:
df = pd.read_csv('./data/AAPL.csv')
df = df.sort_values('Date')

# The algorithms require a vectorized environment to run
env = StockTradingEnv(df)

base_action = np.array([0,0.5])

obs = env.reset()
for i in range(5):
    action, _states = (base_action, None)
    obs, rewards, done, info = env.step(action)
#print(obs)
mod = MyModel(32, (1,4), (1,1))

obs=np.expand_dims(obs,axis=0)
obs=np.expand_dims(obs,axis=0)
print(obs)
z = mod.predict(obs)
print(z)
z = tf.squeeze(z)
print(z)
z = tf.expand_dims(z, 0)
print(z)
z = tf.keras.layers.Dense(1, activation='tanh', kernel_initializer='RandomNormal')(z)
print(z)

[[[[9.95428540e-03 9.99114300e-03 9.93885720e-03 9.96828540e-03
    9.97200020e-03 9.88914260e-03]
   [1.00271430e-02 1.00000000e-02 9.97714300e-03 9.99114300e-03
    1.00000000e-02 9.91771400e-03]
   [9.88714300e-03 9.89171440e-03 9.90085680e-03 9.90457160e-03
    9.86400000e-03 9.77914280e-03]
   [9.90714260e-03 9.90457160e-03 9.93142860e-03 9.98428580e-03
    9.92085720e-03 9.90199960e-03]
   [3.91119626e-02 3.26119363e-02 2.38357112e-02 3.28397844e-02
    3.91155482e-02 3.74857336e-02]
   [1.70822396e-07 4.67606332e-06 9.03382898e-08 9.93109453e-03
    0.00000000e+00 0.00000000e+00]]]]
[[[[-0.00841187]
   [-0.01403271]]]]
tf.Tensor([-0.00841187 -0.01403271], shape=(2,), dtype=float32)
tf.Tensor([[-0.00841187 -0.01403271]], shape=(1, 2), dtype=float32)
tf.Tensor([[-0.00088529]], shape=(1, 1), dtype=float32)


In [4]:
act = StockActor()
act_target = StockActor()
output_action = act(obs)
output_action_tar = act_target(obs)
print("output_action")
print(output_action)
print(" ")
print("output_action_tar")
print(output_action_tar)
print(" ")
output_action = act(obs)
output_action_tar = act_target(obs)
print("output_action2")
print(tf.squeeze(output_action))
print(" ")
print("output_action_tar2")
print(output_action_tar)
print(" ")

#act.model.summary()
#print(act.model.layers[3].get_weights())
#act.model.layers[3].set_weights([np.array([[-0.3]], dtype=np.float32), np.array([0.1], dtype=np.float32)])
#print(act.model.layers[3].get_weights())


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

output_action
tf

In [5]:
a = act.model.trainable_variables
print(a)
print(" ")
print(" ")
print(" hjkbedfhugqdfhiqdfbhiqdf")
print(" ")
print(" ")
b = act.trainable_variables
print(b)

[<tf.Variable 'stock_actor/my_model_1/conv2d_2/kernel:0' shape=(1, 5, 6, 32) dtype=float32, numpy=
array([[[[ 8.16830993e-03, -5.43315709e-02,  5.88549525e-02,
           1.33114547e-01,  2.88731307e-02, -1.17538325e-01,
          -1.59477144e-01,  1.44059509e-01,  1.27195597e-01,
          -7.28294253e-03,  8.93495977e-03,  1.59853101e-02,
           1.67863607e-01,  9.53277946e-03, -2.30015516e-02,
           2.32988149e-02,  1.25740826e-01,  1.16286933e-01,
          -1.39647439e-01, -1.00360692e-01, -1.37211531e-01,
           6.92620873e-02,  5.48256636e-02, -3.71297002e-02,
          -9.61914584e-02, -5.18715531e-02, -9.75433439e-02,
           1.31626785e-01,  5.98482788e-03,  8.37375224e-02,
           5.63436747e-02, -4.44874167e-03],
         [ 3.33580077e-02, -1.26478881e-01, -5.16986847e-02,
           2.27159858e-02, -9.53533724e-02, -3.02046537e-04,
           1.11595809e-01, -8.35054740e-02,  5.43431789e-02,
           8.58703256e-03,  1.04397088e-02, -1.82311535e-02,
  

In [14]:

#model = MyModel(32, (1,4), (1,1))
#output=tf.squeeze(model(obs))

crit = StockCritic()
crit_tar = StockCritic()
crit.action = tf.squeeze(output_action)
crit_tar.action = tf.squeeze(output_action)
output = crit(obs)
output_tar = crit_tar(obs)
print("output")
print(output)
print(" ")
print("output_tar")
print(output_tar)
print(" ")
crit.action = tf.squeeze(output_action_tar)
crit_tar.action = tf.squeeze(output_action)
output = crit(obs)
output_tar = crit_tar(obs)
print("output2")
print(output)
print(" ")
print("output_tar2")
print(output_tar)
print(" ")
print(crit.trainable_variables)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

1

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

1
output
tf.Te